### ISSUE TITLE
Mention Fabric version requirement in readme

### ISSUE THREAD

**Issue by Michael1297** [5zig-reborn/5zig-fabric#1]
logs: [log.txt](https://github.com/5zig-reborn/The-5zig-Mod/files/4275660/log.txt)

mods:
   5zig-Fabric-Installer-1.0.2
   5zig-Reborn-1.14.4-3.13.0
 fabric 0.7.8+build.186
   fabric-api-0.4.2+build.246-1.14
   modmenu-1.7.16.1.14.4+build.128
   optifabric-0.7.1
   OptiFine_1.14.4_HD_U_F5

**Comment by roccodev** [comment]
Should keep this open until we add a note to the readme.

**Comment by roccodev** [comment]
By adding support for 1.15.2, we now also support the latest version of Fabric loader.
